# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kyle Laker
email: kyle@laker.email
description: "" # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kylelaker.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: "kylelaker/jekyll-site"
twitter_username: kyle_laker
github_username:  kylelaker

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed


# Minimal Mistakes settings
minimal_mistakes_skin: "dirt"
author:
  name: "Kyle Laker"
  bio: "Computer science student at James Madison University"
  avatar: "https://avatars0.githubusercontent.com/u/850893?s=460&v=4"
  email: "kyle@laker.email"
  uri: "https://kylelaker.com"
  github: "kylelaker"
  twitter: "kyle_laker"
og_image: "/assets/image/site-logo.png"
twitter:
  username: "kyle_laker"
github:
  username: "kylelaker"
paginate: 5
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
