title: "Kyle Laker"
url: ""
baseurl: ""
email: "kyle@laker.email"
author: Kyle Laker
logo: assets/image/site-logo.png
nav_logo: false

twitter:
  username: kyle_laker
  card: summary
github: kylelaker
linkedin: kyle-laker-0339b346

sass:
  sass_dir: assets/css

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-autoprefixer